In [2]:
import pandas as pd

In [3]:
S=pd.Series([112,32,43,54])
S

0    112
1     32
2     43
3     54
dtype: int64

In [4]:
print(S.index)
print(S.values)

RangeIndex(start=0, stop=4, step=1)
[112  32  43  54]


In [5]:

import numpy as np
X=np.array([11,28,72,34,5])
print(X)
print(S.values)
print(type(S.values),type(X))

[11 28 72 34  5]
[112  32  43  54]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [6]:
fruits=['apple','orange','cherries','pears']
quantities=[20,33,52,10]
S=pd.Series(quantities,index=fruits)
S

apple       20
orange      33
cherries    52
pears       10
dtype: int64

In [7]:
names=['nokesh','sai','bharan','vamsi']
reg_no=[20,33,52,10]
S=pd.Series(reg_no,index=names)
S

nokesh    20
sai       33
bharan    52
vamsi     10
dtype: int64

In [8]:
#d)
S=pd.Series([20,33,52,10],index=fruits)
S2=pd.Series([17,13,31,32],index=fruits)
print(S+S2)
print("Sum of S:",sum(S))

apple       37
orange      46
cherries    83
pears       42
dtype: int64
Sum of S: 115


In [9]:
fruits=['apple','orange','cherries','pears']
fruits=['berry','orange','cherries','pears']
S=pd.Series([20,33,52,10],index=fruits)
S2=pd.Series([17,13,31,32],index=fruits)
print(S+S2)

berry       37
orange      46
cherries    83
pears       42
dtype: int64


In [10]:
import pandas as pd
df = pd.DataFrame({'Brand':['Maruthi','Hyundai','Tata','Mahindra','VolksWagen','Audi','Benz'], 'Year':[2012,2014,2015,2016,2013,2017,2020],
                   'Kms Driven':[50000,60000,65000,70000,75000,80000,85000],'City':['Hyderabad','Kolkata','Bangalore','Chennai','Delhi','Mumbai','Kanpur'],
                   'Mileage':[28,29,27,25,22,26,30]})
display(df)

Brand  Year  Kms Driven       City  Mileage
0     Maruthi  2012       50000  Hyderabad       28
1     Hyundai  2014       60000    Kolkata       29
2        Tata  2015       65000  Bangalore       27
3    Mahindra  2016       70000    Chennai       25
4  VolksWagen  2013       75000      Delhi       22
5        Audi  2017       80000     Mumbai       26
6        Benz  2020       85000     Kanpur       30

In [11]:
display(df.loc[(df.Brand=='Maruthi')&(df.Mileage>25)])

Brand  Year  Kms Driven       City  Mileage
0  Maruthi  2012       50000  Hyderabad       28

In [12]:
#Selecting range of rows from 2 to 5
display(df.loc[2:5])

Brand  Year  Kms Driven       City  Mileage
2        Tata  2015       65000  Bangalore       27
3    Mahindra  2016       70000    Chennai       25
4  VolksWagen  2013       75000      Delhi       22
5        Audi  2017       80000     Mumbai       26

In [13]:
df.loc[2:5, ['Brand', 'Mileage']]

Brand  Mileage
2        Tata       27
3    Mahindra       25
4  VolksWagen       22
5        Audi       26

In [14]:
display(df.loc[(df.Brand=='Maruthi')&(df.Mileage>22)])

Brand  Year  Kms Driven       City  Mileage
0  Maruthi  2012       50000  Hyderabad       28

In [15]:
df.loc[(df.Year<2015),['Mileage']]==22
df

Brand  Year  Kms Driven       City  Mileage
0     Maruthi  2012       50000  Hyderabad       28
1     Hyundai  2014       60000    Kolkata       29
2        Tata  2015       65000  Bangalore       27
3    Mahindra  2016       70000    Chennai       25
4  VolksWagen  2013       75000      Delhi       22
5        Audi  2017       80000     Mumbai       26
6        Benz  2020       85000     Kanpur       30

In [16]:
df.loc[(df.Year<2015),['Mileage']]=22
df

Brand  Year  Kms Driven       City  Mileage
0     Maruthi  2012       50000  Hyderabad       22
1     Hyundai  2014       60000    Kolkata       22
2        Tata  2015       65000  Bangalore       27
3    Mahindra  2016       70000    Chennai       25
4  VolksWagen  2013       75000      Delhi       22
5        Audi  2017       80000     Mumbai       26
6        Benz  2020       85000     Kanpur       30

In [17]:
display(df.iloc[[0,2,4,6]])

Brand  Year  Kms Driven       City  Mileage
0     Maruthi  2012       50000  Hyderabad       22
2        Tata  2015       65000  Bangalore       27
4  VolksWagen  2013       75000      Delhi       22
6        Benz  2020       85000     Kanpur       30

In [18]:
display(df.iloc[1:5,2:4])

Kms Driven       City
1       60000    Kolkata
2       65000  Bangalore
3       70000    Chennai
4       75000      Delhi

In [19]:
import pandas as pd

In [20]:
import pandas as pd
data = {
    'Name':['Alice','Bob','Charlie','David'],
    'Age':[25,30,35,40],
    'Salary':[50000,60000,70000,80000]}
data = pd.DataFrame(data,index=['A','B','C','D'])
data

Name  Age  Salary
A    Alice   25   50000
B      Bob   30   60000
C  Charlie   35   70000
D    David   40   80000

In [21]:
result=data.loc['B']
result

Name        Bob
Age          30
Salary    60000
Name: B, dtype: object

In [22]:
result=data.loc['C','Salary']
result

np.int64(70000)

In [23]:
#1
result=data.iloc[:2,:2]
result

Name  Age
A  Alice   25
B    Bob   30

In [24]:
#2
result=data.iloc[-1,-1]
result

np.int64(80000)

In [25]:
#1
data = data.loc[data['Age'] > 30]
data

Name  Age  Salary
C  Charlie   35   70000
D    David   40   80000

In [26]:
#2
result = data.loc[data['Salary'] > 60000, ['Name', 'Salary']]
result

Name  Salary
C  Charlie   70000
D    David   80000

In [34]:
#4
data.loc['D','Salary']=90000
data

Name   Age   Salary
C  Charlie  35.0  70000.0
D    David  40.0  90000.0
1      NaN  28.0      NaN

In [35]:
#4
data.loc[1,1] = 28  
data

Name   Age   Salary     1
C  Charlie  35.0  70000.0   NaN
D    David  40.0  90000.0   NaN
1      NaN  28.0      NaN  28.0

In [39]:
result=data.loc['B':'D'] 
result

KeyError: 'B'

In [30]:
data.loc[:, ['Age', 'Salary']]
data

Name   Age   Salary
C  Charlie  35.0  70000.0
D    David  40.0  90000.0
1      NaN  28.0      NaN

In [31]:
data.iloc[:3]

Name   Age   Salary
C  Charlie  35.0  70000.0
D    David  40.0  90000.0
1      NaN  28.0      NaN