In [1]:
import pandas as pd
data = {'Name': ['kavi', 'anuj','raj','gautham','reena','ram'],
        'Age': [20,21,19,20,22,23],
        'Gender': ['F','M','M','M','F','M'],
        'Marks': [56,65,'NaN',75,82,99]}
df = pd.DataFrame(data)
df

Name  Age Gender Marks
0     kavi   20      F    56
1     anuj   21      M    65
2      raj   19      M   NaN
3  gautham   20      M    75
4    reena   22      F    82
5      ram   23      M    99

In [2]:
df['Gender']=df['Gender'].map({'M':0,'F':1,}).astype(float)
df

Name  Age  Gender Marks
0     kavi   20     1.0    56
1     anuj   21     0.0    65
2      raj   19     0.0   NaN
3  gautham   20     0.0    75
4    reena   22     1.0    82
5      ram   23     0.0    99

In [3]:
df.filter(['Name'])

Name
0     kavi
1     anuj
2      raj
3  gautham
4    reena
5      ram

In [4]:
df.filter(['Marks'])

Marks
0    56
1    65
2   NaN
3    75
4    82
5    99

In [5]:
df[df['Age']==20]

Name  Age  Gender Marks
0     kavi   20     1.0    56
3  gautham   20     0.0    75

In [6]:
#Merging the data
S_details=pd.DataFrame({
    'ID':[11,12,13,14,15,16,17,18,19,20],
    'Name':['Rahul','ravi','vishnu','nokesh','hari','vasu','raj','gautham','reena','ram'],
    'Branch':['Soas','Soas','Soas','Soas','Soas','Soas','Soas','Soas','Soas','Soas',]})
print(S_details)

   ID     Name Branch
0  11    Rahul   Soas
1  12     ravi   Soas
2  13   vishnu   Soas
3  14   nokesh   Soas
4  15     hari   Soas
5  16     vasu   Soas
6  17      raj   Soas
7  18  gautham   Soas
8  19    reena   Soas
9  20      ram   Soas


In [7]:
Fee_status=pd.DataFrame({
    'ID':[11,12,13,14,15,16,17,18,19,20],
    'Paid':['5000','2000','4000','3000','4000','5000','6000','7000','8000','9000']})
print(Fee_status)

   ID  Paid
0  11  5000
1  12  2000
2  13  4000
3  14  3000
4  15  4000
5  16  5000
6  17  6000
7  18  7000
8  19  8000
9  20  9000


In [8]:
print(pd.merge(S_details,Fee_status,on='ID'))

   ID     Name Branch  Paid
0  11    Rahul   Soas  5000
1  12     ravi   Soas  2000
2  13   vishnu   Soas  4000
3  14   nokesh   Soas  3000
4  15     hari   Soas  4000
5  16     vasu   Soas  5000
6  17      raj   Soas  6000
7  18  gautham   Soas  7000
8  19    reena   Soas  8000
9  20      ram   Soas  9000


In [9]:
#reshaping the data
import numpy as np
array1=np.arange(8)
print("orginal array:\n",array1)

orginal array:
 [0 1 2 3 4 5 6 7]


In [10]:
array2=np.arange(8).reshape(2,4)
print("\n array reshaped with 2 rows and 4 columns:\n",array2)


 array reshaped with 2 rows and 4 columns:
 [[0 1 2 3]
 [4 5 6 7]]


In [11]:
array3=np.arange(8).reshape(4,2)
print("\n array reshaped with 4 rows and 2 columns:\n",array3)


 array reshaped with 4 rows and 2 columns:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [12]:
array4=np.arange(8).reshape(2,2,2)
print("\n orginal array reshaped with 4 rows and 3D:\n",array4)


 orginal array reshaped with 4 rows and 3D:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("q1_dataset.csv")
df

Age Occupation Location  Gender
0     54     Artist     City    Male
1     21     Doctor     City  Female
2     76   Engineer    Rural  Female
3     53     Artist   Suburb    Male
4     45     Doctor    Rural  Female
..   ...        ...      ...     ...
495   78    Teacher   Suburb    Male
496   23   Engineer   Suburb  Female
497   63   Engineer   Suburb    Male
498   36     Artist   Suburb  Female
499   27   Engineer   Suburb    Male

[500 rows x 4 columns]

In [20]:
df.head()

Age Occupation Location  Gender
0   54     Artist     City    Male
1   21     Doctor     City  Female
2   76   Engineer    Rural  Female
3   53     Artist   Suburb    Male
4   45     Doctor    Rural  Female

In [5]:
df.tail()

Age Occupation Location  Gender
495   78    Teacher   Suburb    Male
496   23   Engineer   Suburb  Female
497   63   Engineer   Suburb    Male
498   36     Artist   Suburb  Female
499   27   Engineer   Suburb    Male

In [11]:
#how many observations
num_obesrvations=len(df)
print(f"there are {num_obesrvations} obesravations in the dataset.")

there are 500 obesravations in the dataset.


In [10]:
#how many features
num_features=len(df.columns)
print(f"there are {num_features} obesravations in the dataset.")

there are 4 obesravations in the dataset.


In [12]:
#different occupations
n_occupations= df['Occupation'].unique()
n_occupations

array(['Artist', 'Doctor', 'Engineer', 'Teacher'], dtype=object)

In [13]:
n_occupations= df['Occupation'].nunique()
n_occupations

4

In [14]:
most_common_occupation= df['Occupation'].mode()[0]
print(f"the most_common_occupation is:{most_common_occupation}")

the most_common_occupation is:Artist


In [17]:
average_age=df['Age'].mean()
print(f"the average is:{average_age:.2f}")

the average is:48.51


In [18]:
average_age_per_occupation=df.groupby('Occupation')['Age'].mean()
print("Average age of the people in each occupation in group")
print(average_age_per_occupation)

Average age of the people in each occupation in group
Occupation
Artist      49.475862
Doctor      48.254098
Engineer    49.142857
Teacher     47.024793
Name: Age, dtype: float64


In [22]:
youngest_person_age=df['Age'].min()
youngest_person_occupation=df[df['Age']==youngest_person_age]['Occupation'].iloc[0]

oldest_person_age=df['Age'].min()
oldest_person_occupation=df[df['Age']==oldest_person_age]['Occupation'].iloc[0]

# Print the results
print(f"The occupation of the youngest person is: {youngest_person_occupation}")
print(f"The occupation of the oldest person is: {oldest_person_occupation}")

The occupation of the youngest person is: Artist
The occupation of the oldest person is: Artist


In [23]:
# Find the occupation of the youngest person
youngest_person_occupation = df[df['Age'] == youngest_person_age]['Occupation'].iloc[0]

# Find the oldest person's age
oldest_person_age = df['Age'].max()

# Find the occupation of the oldest person
oldest_person_occupation = df[df['Age'] == oldest_person_age]['Occupation'].iloc[0]

# Print the results
print(f"The occupation of the youngest person is: {youngest_person_occupation}")
print(f"The occupation of the oldest person is: {oldest_person_occupation}")

The occupation of the youngest person is: Artist
The occupation of the oldest person is: Engineer


In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Football_dataset.csv")
df

Team      Tournament  Goals Scored  Shots pg  Yellow Cards  \
0       Manchester City  Premier League            83      15.8            46   
1         Bayern Munich      Bundesliga            99      17.1            44   
2   Paris Saint-Germain         Ligue 1            86      15.0            73   
3             Barcelona          LaLiga            85      15.3            68   
4           Real Madrid          LaLiga            67      14.4            57   
5     Manchester United  Premier League            73      13.8            64   
6              Juventus         Serie A            77      15.7            76   
7           Aston Villa  Premier League            55      13.7            63   
8     Borussia Dortmund      Bundesliga            75      14.6            43   
9       Atletico Madrid          LaLiga            67      12.1           100   
10             Atalanta         Serie A            90      16.3            66   
11              Chelsea  Premier League            58      14.6            49   
12            Liverpool  Premier League            68      16.0            40   
13             AC Milan         Serie A            74      14.7            80   
14                Lille         Ligue 1            64      12.8            67   
15            Tottenham  Premier League            68      11.7            53   
16               Napoli         Serie A            86      17.0            71   
17            Leicester  Premier League            68      12.8            61   
18            Wolfsburg      Bundesliga            61      14.1            56   
19                Inter         Serie A            89      14.5            59   
20                 Lyon         Ligue 1            81      16.1            60   
21           RB Leipzig      Bundesliga            60      16.0            57   
22                Leeds  Premier League            62      13.7            61   
23             West Ham  Premier League            62      12.3            48   
24              Everton  Premier League            47      10.5            59   
25     Bayer Leverkusen      Bundesliga            53      13.0            58   
26  Eintracht Frankfurt      Bundesliga            69      13.2            80   
27               Monaco         Ligue 1            76      12.8            74   
28                 Roma         Serie A            68      14.3            84   

    Red Cards  Shooting Accuracy  AerialsWon  Rating  Discipline  Own Fouls  \
0           2               89.4        12.8    7.01          48          1   
1           3               85.5        12.9    6.95          47          2   
2           7               89.5         9.5    6.88          80          3   
3           2               89.7        10.6    6.87          70          4   
4           2               87.7        11.8    6.86          59          5   
5           1               84.8        14.5    6.85          65          6   
6           6               88.3        11.4    6.85          82          7   
7           4               78.6        19.4    6.84          67          8   
8           1               85.5        12.8    6.84          44          1   
9           0               83.1        14.4    6.84         100          2   
10          3               83.5        16.8    6.84          69          3   
11          3               87.0        15.2    6.83          52          4   
12          0               85.7        14.3    6.82          40          5   
13          4               84.0        15.2    6.82          84          6   
14          2               83.5        15.8    6.82          69          7   
15          2               81.8        16.4    6.81          55          8   
16          3               87.0        11.1    6.81          74          1   
17          0               82.1        16.2    6.80          61          2   
18          3               78.0        16.9    6.80          59          3   
19      

In [3]:
Team= df['Team'].unique()
Team

array(['Manchester City', 'Bayern Munich', 'Paris Saint-Germain',
       'Barcelona', 'Real Madrid', 'Manchester United', 'Juventus',
       'Aston Villa', 'Borussia Dortmund', 'Atletico Madrid', 'Atalanta',
       'Chelsea', 'Liverpool', 'AC Milan', 'Lille', 'Tottenham', 'Napoli',
       'Leicester', 'Wolfsburg', 'Inter', 'Lyon', 'RB Leipzig', 'Leeds',
       'West Ham', 'Everton', 'Bayer Leverkusen', 'Eintracht Frankfurt',
       'Monaco', 'Roma'], dtype=object)

In [7]:
Teams_participated= df['Team'].nunique()
print(f"the number of teams participated in the tournament:{Teams_participated}")

the number of teams participated in the tournament:29


In [16]:
df['Discipline'] = df['Red Cards'] + df['Yellow Cards']
top_teams = df.groupby('Team')['Discipline'].sum().nlargest(2)
print("Top two teams with highest discipline:")
print(top_teams)

Top two teams with highest discipline:
Team
Atletico Madrid    100
Roma                87
Name: Discipline, dtype: int64


In [17]:
df['Discipline'] = df['Red Cards'] + df['Yellow Cards']
top_teams = df.groupby('Team')['Discipline'].sum().nsmallest(2)
print("Top two teams with highest discipline:")
print(top_teams)

Top two teams with highest discipline:
Team
Liverpool            40
Borussia Dortmund    44
Name: Discipline, dtype: int64


In [20]:
average_yellow=df.groupby("Team")['Yellow Cards'].mean()
print(average_yellow)

Team
AC Milan                80.0
Aston Villa             63.0
Atalanta                66.0
Atletico Madrid        100.0
Barcelona               68.0
Bayer Leverkusen        58.0
Bayern Munich           44.0
Borussia Dortmund       43.0
Chelsea                 49.0
Eintracht Frankfurt     80.0
Everton                 59.0
Inter                   59.0
Juventus                76.0
Leeds                   61.0
Leicester               61.0
Lille                   67.0
Liverpool               40.0
Lyon                    60.0
Manchester City         46.0
Manchester United       64.0
Monaco                  74.0
Napoli                  71.0
Paris Saint-Germain     73.0
RB Leipzig              57.0
Real Madrid             57.0
Roma                    84.0
Tottenham               53.0
West Ham                48.0
Wolfsburg               56.0
Name: Yellow Cards, dtype: float64


In [22]:
average_yellow=df['Yellow Cards'].mean()
print(average_yellow)

62.6551724137931


In [25]:
team_goals=df[df['Goals Scored']>5]
num_team_more_5_goals=team_goals['Team'].nunique()
print(f"{num_team_more_5_goals} team scored more then 5 goals")
print("\n the teams the scored more then 5 goals ")
print(team_goals[['Team','Goals Scored']])

29 team scored more then 5 goals

 the teams the scored more then 5 goals 
                   Team  Goals Scored
0       Manchester City            83
1         Bayern Munich            99
2   Paris Saint-Germain            86
3             Barcelona            85
4           Real Madrid            67
5     Manchester United            73
6              Juventus            77
7           Aston Villa            55
8     Borussia Dortmund            75
9       Atletico Madrid            67
10             Atalanta            90
11              Chelsea            58
12            Liverpool            68
13             AC Milan            74
14                Lille            64
15            Tottenham            68
16               Napoli            86
17            Leicester            68
18            Wolfsburg            61
19                Inter            89
20                 Lyon            81
21           RB Leipzig            60
22                Leeds            62
23           

In [26]:
team_goals=df[df['Goals Scored']>5]
num_team_more_5_goals=team_goals['Team'].nunique()
print(team_goals[['Team','Goals Scored']])

                   Team  Goals Scored
0       Manchester City            83
1         Bayern Munich            99
2   Paris Saint-Germain            86
3             Barcelona            85
4           Real Madrid            67
5     Manchester United            73
6              Juventus            77
7           Aston Villa            55
8     Borussia Dortmund            75
9       Atletico Madrid            67
10             Atalanta            90
11              Chelsea            58
12            Liverpool            68
13             AC Milan            74
14                Lille            64
15            Tottenham            68
16               Napoli            86
17            Leicester            68
18            Wolfsburg            61
19                Inter            89
20                 Lyon            81
21           RB Leipzig            60
22                Leeds            62
23             West Ham            62
24              Everton            47
25     Bayer

In [27]:
#which team is most accurate in shooting
most_accurate=df.loc[df['Shooting Accuracy'].idxmax()]
print("\n Teams sorted by shooting accuracy")
print(most_accurate[['Team','Shooting Accuracy']])


 Teams sorted by shooting accuracy
Team                 Barcelona
Shooting Accuracy         89.7
Name: 3, dtype: object
